// ActionTypes.js
export const FETCH_PYQS_REQUEST = 'FETCH_PYQS_REQUEST';
export const FETCH_PYQS_SUCCESS = 'FETCH_PYQS_SUCCESS';
export const FETCH_PYQS_FAILURE = 'FETCH_PYQS_FAILURE';

// export const CREATE_NOTES_REQUEST = 'CREATE_NOTES_REQUEST';
// export const CREATE_NOTES_SUCCESS = 'CREATE_NOTES_SUCCESS';
// export const CREATE_NOTES_FAILURE = 'CREATE_NOTES_FAILURE';

export const DELETE_PYQS_REQUEST = 'DELETE_PYQS_REQUEST';
export const DELETE_PYQS_SUCCESS = 'DELETE_PYQS_SUCCESS';
export const DELETE_PYQS_FAILURE = 'DELETE_PYQS_FAILURE';

