// ActionTypes.js
export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE';

export const FETCH_COURSES_BY_ID_REQUEST = 'FETCH_COURSES_BY_ID_REQUEST';
export const FETCH_COURSES_BY_ID_SUCCESS = 'FETCH_COURSES_BY_ID_SUCCESS';
export const FETCH_COURSES_BY_ID_FAILURE = 'FETCH_COURSES_BY_ID_FAILURE';

export const CREATE_COURSE_REQUEST = 'CREATE_COURSE_REQUEST';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_FAILURE = 'CREATE_COURSE_FAILURE';

export const DELETE_COURSE_REQUEST = 'DELETE_COURSE_REQUEST';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_FAILURE = 'DELETE_COURSE_FAILURE';

export const SEARCH_COURSE_REQUEST = 'SEARCH_COURSE_REQUEST';
export const SEARCH_COURSE_SUCCESS = 'SEARCH_COURSE_SUCCESS';
export const SEARCH_COURSE_FAILURE = 'SEARCH_COURSE_FAILURE';